import test from 'node:test';import assert from 'node:assert/strict';import { createApp } from '../src/worker.js';import { MemoryRepository } from '../src/repository.js';import { MockAIProvider } from '../src/ai.js';
const env={WEB_PASSWORD:'web-test-password',SESSION_SECRET:'session-test-secret',GPT_ACTION_SECRET:'gpt-test-secret',AI_PROVIDER:'mock'};
const idea={title:'保存テスト',original_question:'どう保存する？',summary:'保存方法を相談した。',conclusion:'明示操作で保存する。',unresolved_items:[],next_actions:['試す'],ai_suggestions:[],kind:'decision',category:'開発',tags:['memo'],importance:'high',source_excerpt:'保存'};
async function session(app){const r=await app(new Request('https://test/api/v1/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:env.WEB_PASSWORD})}),env);const data=await r.json();return{cookie:r.headers.get('set-cookie').split(';')[0],csrf:data.csrf_token};}
const req=(path,{method='GET',body,auth}={})=>new Request(`https://test${path}`,{method,headers:{...(body?{'content-type':'application/json'}:{}),...(auth?{cookie:auth.cookie,'x-csrf-token':auth.csrf}:{})},body:body?JSON.stringify(body):undefined});
test('unauthenticated APIs and invalid GPT secret are rejected',async()=>{const app=createApp({repo:new MemoryRepository()});assert.equal((await app(req('/api/v1/ideas'),env)).status,401);assert.equal((await app(new Request('https://test/api/v1/ideas/from-gpt',{method:'POST',headers:{authorization:'Bearer wrong','content-type':'application/json'},body:JSON.stringify(idea)}),env)).status,401)});
test('raw import creates capture then idea, list, and detail',async()=>{const repo=new MemoryRepository();const app=createApp({repo,ai:new MockAIProvider()});const auth=await session(app);const imported=await app(req('/api/v1/captures/import',{method:'POST',body:{raw_text:'仕事の会議を短くしたい。議題を先に共有する。'},auth}),env);assert.equal(imported.status,201);const data=await imported.json();assert.equal(data.capture.processing_status,'ready');assert.ok(data.idea.id);assert.equal((await repo.getCapture(data.capture.id)).raw_text.includes('会議'),true);const list=await (await app(req('/api/v1/ideas',{auth}),env)).json();assert.equal(list.ideas.length,1);const detail=await (await app(req(`/api/v1/ideas/${data.idea.id}`,{auth}),env)).json();assert.equal(detail.idea.tags[0],'import')});
test('AI failure preserves raw text and retry succeeds',async()=>{const repo=new MemoryRepository();let fail=true;const ai={structure:async raw=>{if(fail)throw new Error('provider unavailable');return new MockAIProvider().structure(raw)}};const app=createApp({repo,ai});const auth=await session(app);const response=await app(req('/api/v1/captures/import',{method:'POST',body:{raw_text:'失敗しても残す文章'},auth}),env);assert.equal(response.status,202);const {capture}=await response.json();assert.equal(capture.processing_status,'failed');assert.equal(capture.raw_text,'失敗しても残す文章');fail=false;const retry=await app(req(`/api/v1/captures/${capture.id}/process`,{method:'POST',body:{},auth}),env);assert.equal(retry.status,200);assert.equal((await retry.json()).idea.title,'失敗しても残す文章')});
test('duplicate imports and GPT Action are idempotent',async()=>{const repo=new MemoryRepository();const app=createApp({repo,ai:new MockAIProvider()});const auth=await session(app);const first=await (await app(req('/api/v1/captures/import',{method:'POST',body:{raw_text:'同じ文章'},auth}),env)).json();const second=await (await app(req('/api/v1/captures/import',{method:'POST',body:{raw_text:'同じ文章'},auth}),env)).json();assert.equal(second.duplicate,true);assert.equal(second.capture.id,first.capture.id);const send=()=>app(new Request('https://test/api/v1/ideas/from-gpt',{method:'POST',headers:{authorization:`Bearer ${env.GPT_ACTION_SECRET}`,'content-type':'application/json'},body:JSON.stringify(idea)}),env);assert.equal((await send()).status,201);const duplicate=await send();assert.equal(duplicate.status,200);assert.equal((await duplicate.json()).duplicate,true)});
test('invalid JSON, empty, huge, CSRF, and XSS text are handled',async()=>{const repo=new MemoryRepository();const app=createApp({repo});const auth=await session(app);assert.equal((await app(new Request('https://test/api/v1/captures/import',{method:'POST',headers:{cookie:auth.cookie,'x-csrf-token':auth.csrf,'content-type':'application/json'},body:'{'}),env)).status,400);assert.equal((await app(req('/api/v1/captures/import',{method:'POST',body:{raw_text:''},auth}),env)).status,400);assert.equal((await app(req('/api/v1/captures/import',{method:'POST',body:{raw_text:'x'.repeat(500001)},auth}),env)).status,400);assert.equal((await app(new Request('https://test/api/v1/captures/import',{method:'POST',headers:{cookie:auth.cookie,'content-type':'application/json'},body:JSON.stringify({raw_text:'csrf'})}),env)).status,403);const xss=await app(req('/api/v1/captures/import',{method:'POST',body:{raw_text:'<script>alert(1)</script>'},auth}),env);assert.equal(xss.status,201);assert.match(xss.headers.get('content-type'),/^application\/json/)});
test('session endpoint restores CSRF and DB errors hide details',async()=>{const app=createApp({repo:new MemoryRepository()});const auth=await session(app);const restored=await (await app(new Request('https://test/api/v1/auth/session',{headers:{cookie:auth.cookie}}),env)).json();assert.equal(restored.csrf_token,auth.csrf);const broken=createApp({repo:{listIdeas:async()=>{throw new Error('database password secret-value')}}});const response=await broken(new Request('https://test/api/v1/ideas',{headers:{cookie:auth.cookie}}),env);assert.equal(response.status,500);assert.equal((await response.json()).error.message,'Internal server error')});
